name: Deploy Laravel Otomatis

on:
  push:
    branches:
      - main  # Pastikan sesuai dengan nama branch utama lu

jobs:
  web-deploy:
    name: Sync Files
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode Terbaru
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 📦 Step 1.A: Bungkus Logic ke ZIP (Anti-Block)
        run: zip -q -r deploy.zip . -x "**/.git**" "**/vendor/**" "**/node_modules/**" "public/**" ".env" "bootstrap/cache/**"

      - name: 🚀 Step 1.B: Kirim ZIP via cURL
        run: curl -T deploy.zip ftp://${{ secrets.FTP_SERVER }}/domains/hanascake.syauqiebill.my.id/public_html/deploy.zip --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}"

      - name: 📦 Step 2.A: Bungkus Tampilan (Frontend) ke ZIP
        run: |
          cd public
          zip -q -r ../public.zip . -x "assets/modules/**"
          cd ..

      - name: 🚀 Step 2.B: Kirim ZIP Tampilan via cURL
        run: curl -T public.zip ftp://${{ secrets.FTP_SERVER }}/domains/hanascake.syauqiebill.my.id/public_html/public.zip --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}"