name: Deploy Laravel Otomatis

on:
  push:
    branches:
      - main  # Ganti jadi 'master' kalau kamu pakai nama master

jobs:
  web-deploy:
    name: Sync Files
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode Terbaru
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Kirim File lewat FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp  # Paksa jalur biasa
          port: 21
          security: loose
          timeout: 120000
          # exclude biarin sama kayak sebelumnya
          max-parallel: 5
          # Pengecualian file:
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/storage/logs/**
            **/storage/framework/sessions/**
            **/public_html/**
            .env
            public/assets/**
            bootstrap/cache/**
